// <auto-generated />
namespace Task1.Infrastructure.Migrations.Students
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LastVersionLocal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastVersionLocal));
        
        string IMigrationMetadata.Id
        {
            get { return "201610312133261_LastVersionLocal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
