// <auto-generated />
namespace Task1.Infrastructure.Migrations.Students
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AnotherVersion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnotherVersion));
        
        string IMigrationMetadata.Id
        {
            get { return "201610312134339_AnotherVersion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
